name: Root
version: "0.3.1"
main: com.github.valkyrienyanko.constantine.Root
commands:
  discord:
    description: Discord link
  store:
    description: Store link
  teamspeak:
    description: Teamspeak link
    aliases: [ts]
  website:
    description: Website link
  help:
    description: Show help
  points:
    descriotion: Show points
    aliases: [pts, pt]
  root:
    description: Root plugin management

permissions:
  root.reload:
    description: Allows the usage of /root reload
    default: op

load: STARTUP